source 'http://rubygems.org'

gem 'plutus', path: '../'
gem 'rails', '5.0.0'
gem 'sqlite3'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

group :test do
  # Pretty printed test output
  gem 'turn', require: false
end

group :development do
  gem 'spring'
  gem 'web-console', '~> 3.1.1'
end
