source 'http://rubygems.org'

gem 'plutus', path: '../'
gem 'rails', '>= 4.0'
gem 'sqlite3'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

group :development do
  gem 'web-console', '~> 2.0'
end
